version: '3'
services:
  cassandra1:
    hostname: cassandra1
    image: cassandra:latest
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    ports:
      - "7000:17000"
      - "7001:17001"
      - "7199:17199"
      - "9042:19042"
      - "9160:19160"
  cassandra2:
    hostname: cassandra2
    image: cassandra:latest
    environment:
      - CASSANDRA_SEEDS=cassandra1
    links:
      - cassandra1:cassandra
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    ports:
      - "9042:19043"
    depends_on:
      - cassandra1